### ISSUE TITLE
Scripts to be created from .ipynb file

### ISSUE THREAD

**Issue by SimplyTim** [UBC-MDS/wine_quality_predictor_group1#19]
The following were the sections in the `.ipynb` file that involved code were as follows:

* Loading Data
* Data Cleaning
* Data Validation
* Data Splitting
* EDA
* Analysis

We can each work on the part we did for Milestone 1, if that's acceptable to everyone.
We can collaborate on the work on the Quarto file.

Let me know what you think. Thanks!

**Comment by wzhu8410** [comment]
Script work distribution:

- Data Loading, Cleaning @yixuangaoclara 
- Data splitting, EDA @BryanLee06 
- Model training, Model evaluation (matrix in the end) @SimplyTim 
- Tuning, Data validation @wzhu8410

**Comment by yixuangaoclara** [comment]
I created a folder - scripts, added download_data.py and clean_data.py into the folder, and also updated the README file.

**Comment by yixuangaoclara** [comment]
**Checklist for the Milestone3:**

1. Scripts:

- Loading Data
- Data Cleaning
- Data Validation
- Data Splitting
- EDA
- Analysis

Document in the README.md how to call each script, including what arguments you pass each script

2. Use "quarto convert notebook.ipynb --to qmd" to convert Jupyter notebooks to *.qmd files

3. Edit the .qmd file:

- Create a table of contents using markdown headers and Quarto configuration
- Add BibTeX references
- Edit figure format (automatically number figures, cross reference, control sizes)
- Add a table description argument
- Replace any hard-coded values in the Quarto report narrative text with inline Quarto code
- Change the code chunk options so that no code is viewable in the rendered report
- Render the report to either HTML or PDF

4. Update the project’s computational environment:

- Add packages with pinned version
- Rebuild the Docker container image
- Publish to DockerHub
- Update README.md

**Comment by SimplyTim** [comment]
Completed. Creating release now. Thanks team!
